### ISSUE TITLE
Unexpected results when using `length_per_key` in `KeyedJaggedTensor`

### ISSUE THREAD

**Issue by nathancooperjones** [meta-pytorch/torchrec#1075]
Hi Torchrec team! 

I ran into (what I thought was) an unexpected result when experimenting with different ways to instantiate a `KeyedJaggedTensor`. In my use case, I might have a query where we have more item embeddings to retrieve than we have users. In this case, using the `length_per_key` argument when instantiating a `KeyedJaggedTensor` lead to a string representation which didn't match the `.values()` returned by the object. 

For example, consider we are trying to retrieve: 

```
|---------|---------|
| user ID | item ID |
|---------|---------|
| [1]     | [4]     |
| [2]     | [5]     |
| [3]     | [6]     |
| []      | [7]     |
| []      | [8]     |
|---------|---------|
```

The expected way to instantiate this using the `lengths` keyword argument appears to be:

```python
# this works!
jagged_tensor_right = torchrec.KeyedJaggedTensor(
    keys=['user', 'item'],
    values=torch.tensor(data=[1, 2, 3, 4, 5, 6, 7, 8], device='cuda:0'),
    lengths=torch.tensor(data=[1, 1, 1, 0, 0, 1, 1, 1, 1, 1], device='cuda:0'),
)

print(jagged_tensor_right)
# KeyedJaggedTensor({
#    "user": [[1], [2], [3], [], []],
#    "item": [[4], [5], [6], [7], [8]]
# })
```

As expected, looking through the values for `user`, we get:

```python
jagged_tensor_right['user'].values()
# tensor([1, 2, 3], device='cuda:0')
```

However, if trying to use `length_per_key` as well and avoid putting `0`s in `lengths`, it _appears_ that we get the wrong representation:

```python
# this does NOT work!
jagged_tensor_wrong = torchrec.KeyedJaggedTensor(
    keys=['user', 'item'],
    values=torch.tensor(data=[1, 2, 3, 4, 5, 6, 7, 8], device='cuda:0'),
    lengths=torch.tensor(data=[1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0'),  # note there are no 0s here
    length_per_key=(3, 5),  # added argument here
)

print(jagged_tensor_wrong)
# KeyedJaggedTensor({
#     "user": [[1], [2], [3], [4]],
#     "item": [[5], [6], [7], [8]]
# })
```

BUT, this is the interesting part: if looking at the values of `user` again, it is somehow "correct", seemingly contradicting the above string representation:

```python
jagged_tensor_wrong['user'].values()
# tensor([1, 2, 3], device='cuda:0')
```

When used in a model, the user values will, however, still be `[1, 2, 3, 4]`, not what is printed out in `jagged_tensor_wrong['user'].values()`. 

Does this seem like expected behavior? If so, is there a good resource I can see on how to properly use `length_per_key` to get expected results?

**Comment by joshuadeng** [comment]
Hi @nathancooperjones, thanks for raising the concern. 

Actually the KJT is behaving correctly in this instance. In the second example, you removed the 0s from the lengths, which implicitly makes the stride (batch size) 4, instead of 5 in the first case. It's necessary to include the 0s so that the KJT knows the last 2 samples for the user are empty, as the stride is implicitly calculated in the constructor and KJT does not support variable batch.

When passing in optional constructor args like `length_per_key`, we don't do any validation for perf reasons and assume correctness on the user. So in the first example `length_per_key = [3, 5]`, but in the second example `length_per_key = [4, 4]`.

Hope this helps!
