### ISSUE TITLE
Categorical Input Dimension Limit

### ISSUE THREAD

**Issue by ayasar70** [meta-pytorch/torchrec#1125]
Hello, when I tried to give an embedding dimension >1024 I receive the following error: 

``RuntimeError: Expected max_D <= 1024 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)``

Is there a way to overcome this issue and work with larger embeddings?

**Comment by joshuadeng** [comment]
hi @ayasar70,

The max embedding dim check is set in FBGEMM [here](https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/codegen/embedding_backward_code_generator.py#L44). This was previously set due to shared memory limitation, but currently is limited by the binary size / compilation time. You can try changing this value locally, but it might require recompiling FBGEMM.

Alternatively, you can create multiple embedding tables with the same feature as a workaround.

Thanks!

**Comment by dmudigere** [comment]
For the larger  emb_dims , in addition to disabling the check and recompiling - are there alternate kernel(s)/optimization that should be used ? (cc: @jianyuh, @jspark1105)

**Comment by YLGH** [comment]
Another workout could be to create two tables (one with 1024 embedding dim, the other with the extra dims). You may need some additional logic to stitch it together, but is good unblocker if you don't want to recompile FBGEMM
