### ISSUE TITLE
automatic planner and customized planning

### ISSUE THREAD

**Issue by xiexbing** [meta-pytorch/torchrec#1257]
Hello,

Is there any detailed document discussing the automatic parallelism planning? I want to know details on how the user inputs are included in the planning process and how torchrec make decisions. Moreover, I see some other documents mentioning about sorting the embedding tables for table wise parallelism to balance the load across accelerators, which suggests the customization of parallelism planning, I didn't see the interfaces from torchrec for this, how to realize it?

**Comment by YLGH** [comment]
Hey @xiexbing, check out

https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/planner/Planner_Introduction.ipynb

and the related folders.

Planner allows your to customize your enumerator (sharding strategies per table), cost estimators, partitioner, and allocator.

>  I want to know details on how the user inputs are included in the planning process and how torchrec make decisions

The main thing planner uses is the pooling factor (embedding lookup takes more time w/ larger pooling factor, so in order to balance embedding lookups, this needs to be taken into account).
