### ISSUE TITLE
How to freeze params of an embedding table in EmbeddingBagCollection？

### ISSUE THREAD

**Issue by tiankongdeguiji** [meta-pytorch/torchrec#1990]

**Comment by tiankongdeguiji** [comment]
Hi, @henrylhtsang  @IvanKobzarev  @joshuadeng  @PaulZhang12  can you see this problem?

**Comment by colin2328** [comment]
a few ways you could do this:
the simplest way would be to constrain (through parameter constraints) your EBC to be dense (non fused) and not to set up an optimizer for the tables you want to freeze.
You could also try setting the lr to 0 if you are interested in freezing EBCs mid training.

Keep in mind htat if you have only some tables you want to freeze (and some you want to always be trainable) that you wil likely want to create separate EBCs for each (otherwise the sharder might combine them)

**Comment by tiankongdeguiji** [comment]
> a few ways you could do this: the simplest way would be to constrain (through parameter constraints) your EBC to be dense (non fused) and not to set up an optimizer for the tables you want to freeze. You could also try setting the lr to 0 if you are interested in freezing EBCs mid training.
> 
> Keep in mind htat if you have only some tables you want to freeze (and some you want to always be trainable) that you wil likely want to create separate EBCs for each (otherwise the sharder might combine them)

Thanks!

**Comment by threestone965** [comment]
> a few ways you could do this: the simplest way would be to constrain (through parameter constraints) your EBC to be dense (non fused) and not to set up an optimizer for the tables you want to freeze. You could also try setting the lr to 0 if you are interested in freezing EBCs mid training.
> 
> Keep in mind htat if you have only some tables you want to freeze (and some you want to always be trainable) that you wil likely want to create separate EBCs for each (otherwise the sharder might combine them)

i want to freeze EmbeddingCollection mid training,  but the method that set lr to 0 can't save memory and computing resources. is there a method similar to the following code. looking forward to your reply, thanks
```
for param in module.parameters():
        param.requires_grad = False
```
