### ISSUE TITLE
AttributeError: '_OpNamespace' object has no attribute 'permute_2D_sparse_data'

### ISSUE THREAD

**Issue by rllin** [meta-pytorch/torchrec#524]
dependencies:
`fbgemm-gpu-nightly-cpu==2022.6.28`
`torchrec==0.2.0`
`torch==1.12.0`

it is a bit hard for me to disentangle code to easily give a repro, but this seems less a problem with code and more with dependencies?

```
E           raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
E       AttributeError: '_OpNamespace' object has no attribute 'permute_2D_sparse_data'
```

**Comment by colin2328** [comment]
Hi @rllin ,

Ack, will try to test.
To confirm you are trying to run this on a non CUDA enabled machine (CPU only, right?)

Is there a reason you aer using fbgemm-gpu-nightly-cpu instead of the stable version  of fbgemm cpu? (i.e fbgemm-gpu-cpu)

**Comment by rllin** [comment]
i also just tried `fbgemm-gpu-cpu==0.2.0` and saw the same thing

**Comment by rllin** [comment]
looks like a torch 1.12.0+cu113 was sneaking into my installs.  when i force it to be 1.12.0 without cu113, this works!

**Comment by BichengWang** [comment]
Same issue when I "import torchrec".
```
torch==1.14.0.dev20221105+cu117
torchaudio==0.14.0.dev20221106+cu117
torchmetrics==0.10.2
torchrec-nightly==2022.11.5
torchvision==0.15.0.dev20221106+cu117
torchx-nightly==2022.11.6
```

**Comment by rllin** [comment]
I'm seeing this now with this `Dockerfile`

```
FROM python:3.8.13-slim-bullseye

RUN pip install \
  torch==1.12.0 \
  && rm -rf /root/.cache/pip

RUN pip uninstall -y fbgemm-gpu==0.2.0
RUN pip install \
  torchrec==0.2.0
RUN pip install \
  fbgemm-gpu-cpu==0.2.0

```

Any ideas?

**Comment by rllin** [comment]
hmm ok looks like using `python:3.7.16-slim` works

**Comment by master0v** [comment]
why does this have anything to do with cuda?  Isn't this about a simple file reading operation?

**Comment by tarano297** [comment]
Hello
What should I do to fix the following bug in Ubuntu?
Access the code using the following url
https://github.com/facebookresearch/dlrm

**Comment by tarano297** [comment]
bug in code:AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

**Comment by colin2328** [comment]
@tarano297 , can you comment on your dependencies and environment?
which pytorch version, which fbgemm version, which torchrec version?

cc @henrylhtsang

**Comment by tarano297** [comment]
> @tarano297 , can you comment on your dependencies and environment? which pytorch version, which fbgemm version, which torchrec version?
> 
> cc @henrylhtsang

I can't install pytorch, fbgemm and torchrec packages in ubuntu terminal.
Can you guide me please?

**Comment by henrylhtsang** [comment]
@tarano297 Can you try installing pytorch using pip first? 

you can follow here https://pytorch.org/get-started/locally/

**Comment by tarano297** [comment]
hi,
I got this error massage in Ubuntu 16.04 what should I do?
 sudo apt update
 Err:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Could not resolve 'security.ubuntu.com'
Hit:2 http://ir.archive.ubuntu.com/ubuntu xenial InRelease                                 
Hit:3 http://ir.archive.ubuntu.com/ubuntu xenial-updates InRelease                         
Hit:4 http://ir.archive.ubuntu.com/ubuntu xenial-backports InRelease                 
Get:5 http://ppa.launchpad.net/canonical-hwe-team/backport-iwlwifi/ubuntu xenial InRelease [17.5 kB]
Err:5 http://ppa.launchpad.net/canonical-hwe-team/backport-iwlwifi/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23BEB290D9AAAA49
Ign:6 https://apt.releases.hashicorp.com xenial InRelease
Err:7 https://apt.releases.hashicorp.com xenial Release
  404  Not Found
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/canonical-hwe-team/backport-iwlwifi/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23BEB290D9AAAA49
E: The repository 'http://ppa.launchpad.net/canonical-hwe-team/backport-iwlwifi/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://apt.releases.hashicorp.com xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by opringle** [comment]
I was able to get things working on a machine with no gpu by setting up my environment as follows:

Dockerfile
```docker
FROM python:3.9

RUN pip install torch==2.1.1 && \
    pip install numpy==1.26.2 && \
    pip install fbgemm-gpu==0.5.0 --index-url https://download.pytorch.org/whl/cpu && \
    pip install torchrec==0.5.0
```

**Comment by Ross-Fan** [comment]
Almost the same problem occurred in my environment,  in pytorch 1.13.1, the error is:
'fbgemm' object has no attribute 'jagged_2d_to_dense'
I assume that torchrec may just fit for the torch2.x, so I uninstall the 1.13.1, install the latest version:2.1.2+cpu
It works~
btw, my environment is cpu-only
